Dataset sourced from https://www.kaggle.com/datasets/shashwatwork/web-page-phishing-detection-dataset

## Additional data processing to match ultra safe features to ensure more accuracy

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset_phishing.csv')
df2 = df.copy()
df3 = pd.DataFrame()

In [3]:
def extract_domain(dom):
    d = str(dom)
    return d.replace("http://", "").replace("https://", "").split("/")[0]
df2['url'] = df.url.apply(extract_domain)

In [4]:
df3

Empty DataFrame
Columns: []
Index: []

In [5]:
ultra_safe_features = [
    'DomainLength',
    'TLD',
    'TLDLength',
    'NoOfSubDomain',
    'LetterRatioInURL',
    'label'
]

In [6]:
df3['DomainLength'] = df2.url.apply(lambda x: len(x))

In [7]:
df3['TLD'] = df2.url.apply(lambda x: x.split(".")[-1])

In [8]:
df3['TLDLength'] = df3.TLD.apply(lambda x: len(x))

In [9]:
df3['NoOfSubDomain'] = df2.url.apply(lambda x: len(x.split(".")) - 2)

In [10]:
import re
from difflib import SequenceMatcher
df3['LetterRatioInURL'] = df2.url.apply(lambda x: SequenceMatcher(a="".join(re.findall(r'[a-zA-Z]+', x)), b=x).ratio())

In [11]:
df3['label'] = df2.status.apply(lambda x: 0 if (x == "phishing") else 1)

In [12]:
df3

       DomainLength  TLD  TLDLength  NoOfSubDomain  LetterRatioInURL  label
0                19  com          3              1          0.944444      1
1                23  com          3              0          0.977778      0
2                50  com          3              3          0.947368      0
3                11   in          2              1          0.900000      1
4                15  com          3              1          0.928571      1
...             ...  ...        ...            ...               ...    ...
11425            17  com          3              1          0.937500      1
11426            18  com          3              1          0.941176      0
11427            16  com          3              1          0.933333      1
11428            30  com          3              1          0.965517      1
11429            14  123          3              2          0.000000      0

[11430 rows x 6 columns]

In [13]:
df3.drop_duplicates()

       DomainLength  TLD  TLDLength  NoOfSubDomain  LetterRatioInURL  label
0                19  com          3              1          0.944444      1
1                23  com          3              0          0.977778      0
2                50  com          3              3          0.947368      0
3                11   in          2              1          0.900000      1
4                15  com          3              1          0.928571      1
...             ...  ...        ...            ...               ...    ...
11385            19  com          3              1          0.882353      0
11387            19   nz          2              2          0.882353      0
11393            77   se          2              6          0.727273      0
11397             6   no          2              0          0.909091      1
11404            10   es          2              0          0.947368      0

[2918 rows x 6 columns]

In [14]:
df3.to_csv('additional_phishing_ds.csv')